class Style < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'ボヘミアン・ピルスナー' },
    { id: 3, name: 'ジャーマン・ピルスナー' },
    { id: 4, name: 'シュバルツ' },
    { id: 5, name: 'ドルトムンダー' },
    { id: 6, name: 'アメリカンラガー' },
    { id: 7, name: 'ウィンナーラガー' },
    { id: 8, name: 'ドッペルボック' },
    { id: 9, name: 'ペールエール' },
    { id: 10, name: 'IPA' },
    { id: 11, name: 'スタウト' },
    { id: 12, name: '修道院ビール' },
    { id: 13, name: 'ホワイトエール' },
    { id: 14, name: 'バーレイワイン' },
    { id: 15, name: 'ヴァイツェン' },
    { id: 16, name: 'ポーター' },
    { id: 17, name: 'セゾン' },
    { id: 18, name: 'ヘーフェヴァイツェン' },
    { id: 19, name: 'スコッチエール' },
    { id: 20, name: 'トラピストビール' },
    { id: 21, name: 'ランビック' },
    { id: 22, name: 'フルーツビール' },
    { id: 23, name: 'グーズ' },
    { id: 24, name: '木片・木樽熟成ビール' },
    { id: 25, name: 'チョコレートビール' },
    { id: 26, name: 'その他' }
  ]
end
